apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
  annotations:
    user: {{ required "A valid .Values.user entry required!" .Values.user }}
    password: {{ required "A valid .Values.password entry required!" .Values.password }}
stringData:
  auth: {{ htpasswd .Values.user .Values.password }}
